/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersionsIndexRouteImport } from './routes/versions/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as InstallationsIndexRouteImport } from './routes/installations/index'
import { Route as ServersPublicRouteImport } from './routes/servers/public'
import { Route as InstallationsWorldsRouteImport } from './routes/installations/worlds'
import { Route as InstallationsModsRouteImport } from './routes/installations/mods'
import { Route as InstallationsLogsRouteImport } from './routes/installations/logs'

const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsIndexRoute = VersionsIndexRouteImport.update({
  id: '/versions/',
  path: '/versions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsIndexRoute = InstallationsIndexRouteImport.update({
  id: '/installations/',
  path: '/installations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersPublicRoute = ServersPublicRouteImport.update({
  id: '/servers/public',
  path: '/servers/public',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsWorldsRoute = InstallationsWorldsRouteImport.update({
  id: '/installations/worlds',
  path: '/installations/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsModsRoute = InstallationsModsRouteImport.update({
  id: '/installations/mods',
  path: '/installations/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsLogsRoute = InstallationsLogsRouteImport.update({
  id: '/installations/logs',
  path: '/installations/logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/installations/logs': typeof InstallationsLogsRoute
  '/installations/mods': typeof InstallationsModsRoute
  '/installations/worlds': typeof InstallationsWorldsRoute
  '/servers/public': typeof ServersPublicRoute
  '/installations/': typeof InstallationsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/versions/': typeof VersionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/installations/logs': typeof InstallationsLogsRoute
  '/installations/mods': typeof InstallationsModsRoute
  '/installations/worlds': typeof InstallationsWorldsRoute
  '/servers/public': typeof ServersPublicRoute
  '/installations': typeof InstallationsIndexRoute
  '/news': typeof NewsIndexRoute
  '/servers': typeof ServersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/versions': typeof VersionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logs': typeof LogsRoute
  '/installations/logs': typeof InstallationsLogsRoute
  '/installations/mods': typeof InstallationsModsRoute
  '/installations/worlds': typeof InstallationsWorldsRoute
  '/servers/public': typeof ServersPublicRoute
  '/installations/': typeof InstallationsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/versions/': typeof VersionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/installations/logs'
    | '/installations/mods'
    | '/installations/worlds'
    | '/servers/public'
    | '/installations/'
    | '/news/'
    | '/servers/'
    | '/settings/'
    | '/versions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logs'
    | '/installations/logs'
    | '/installations/mods'
    | '/installations/worlds'
    | '/servers/public'
    | '/installations'
    | '/news'
    | '/servers'
    | '/settings'
    | '/versions'
  id:
    | '__root__'
    | '/'
    | '/logs'
    | '/installations/logs'
    | '/installations/mods'
    | '/installations/worlds'
    | '/servers/public'
    | '/installations/'
    | '/news/'
    | '/servers/'
    | '/settings/'
    | '/versions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogsRoute: typeof LogsRoute
  InstallationsLogsRoute: typeof InstallationsLogsRoute
  InstallationsModsRoute: typeof InstallationsModsRoute
  InstallationsWorldsRoute: typeof InstallationsWorldsRoute
  ServersPublicRoute: typeof ServersPublicRoute
  InstallationsIndexRoute: typeof InstallationsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ServersIndexRoute: typeof ServersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  VersionsIndexRoute: typeof VersionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions/': {
      id: '/versions/'
      path: '/versions'
      fullPath: '/versions/'
      preLoaderRoute: typeof VersionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/': {
      id: '/installations/'
      path: '/installations'
      fullPath: '/installations/'
      preLoaderRoute: typeof InstallationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/public': {
      id: '/servers/public'
      path: '/servers/public'
      fullPath: '/servers/public'
      preLoaderRoute: typeof ServersPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/worlds': {
      id: '/installations/worlds'
      path: '/installations/worlds'
      fullPath: '/installations/worlds'
      preLoaderRoute: typeof InstallationsWorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/mods': {
      id: '/installations/mods'
      path: '/installations/mods'
      fullPath: '/installations/mods'
      preLoaderRoute: typeof InstallationsModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/logs': {
      id: '/installations/logs'
      path: '/installations/logs'
      fullPath: '/installations/logs'
      preLoaderRoute: typeof InstallationsLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogsRoute: LogsRoute,
  InstallationsLogsRoute: InstallationsLogsRoute,
  InstallationsModsRoute: InstallationsModsRoute,
  InstallationsWorldsRoute: InstallationsWorldsRoute,
  ServersPublicRoute: ServersPublicRoute,
  InstallationsIndexRoute: InstallationsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ServersIndexRoute: ServersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  VersionsIndexRoute: VersionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
